# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IHAM_loginAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='promoName',
            new_name='promoCode',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='created_on',
        ),
    ]
