# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHAM_app', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='promoCode',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
