# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHAM_app', '0004_upcomingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleIndo', models.TextField()),
                ('titleEng', models.TextField()),
                ('isiIndo', models.TextField()),
                ('isiEng', models.TextField()),
            ],
        ),
    ]
