# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHAM_app', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='deliveredFlage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='paidFlage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='productPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='shippingPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
