# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHAM_app', '0007_auto_20180120_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='customerPhone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='grandTotalPrice',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='productPrice',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='shippingPrice',
            field=models.BigIntegerField(),
        ),
    ]
